send_tts:
  name: 发送TTS消息
  description: 向小智设备发送文本转语音消息，设备将播放此消息内容。
  target:
    entity:
      integration: xiaozhi
      domain: binary_sensor
  fields:
    device_id:
      name: 设备ID
      description: 要发送消息的小智设备ID
      required: true
      example: "xiaozhi_device1"
      selector:
        text:
    message:
      name: 消息内容
      description: 要播放的文本消息
      required: true
      example: "这是一条测试消息"
      selector:
        text:

get_device_config:
  name: 获取设备配置
  description: 生成用于ESP32设备的配置信息，包括WebSocket URL和设备ID等信息。
  fields:
    config_entry_id:
      name: 配置条目ID
      description: 小智集成的配置条目ID
      required: true
      example: "a1b2c3d4"
      selector:
        text:
    device_id:
      name: 设备ID
      description: 为ESP32设备配置的ID，建议使用简短且唯一的标识符
      required: false
      default: "xiaozhi_device"
      example: "kitchen_assistant"
      selector:
        text:
    fallback_url:
      name: 备选URL
      description: 如果无法自动获取Home Assistant外部URL，则使用此URL作为备选
      required: false
      example: "http://192.168.1.100:8123"
      selector:
        text:

restart_websocket:
  name: 重启WebSocket服务
  description: 重新启动小智ESP32的WebSocket服务器，可用于解决连接问题。
  target:
    entity:
      integration: xiaozhi
      domain: binary_sensor
  fields:
    config_entry_id:
      name: 配置条目ID
      description: 小智集成的配置条目ID
      required: true
      example: "a1b2c3d4"
      selector:
        text:

send_notification:
  name: 发送通知
  description: 向小智设备发送通知消息，设备将通过LED指示灯和语音播报通知用户。
  target:
    entity:
      integration: xiaozhi
      domain: binary_sensor
  fields:
    device_id:
      name: 设备ID
      description: 要接收通知的小智设备ID
      required: true
      example: "xiaozhi_device1"
      selector:
        text:
    message:
      name: 通知内容
      description: 通知消息内容
      required: true
      example: "有人按门铃了"
      selector:
        text:
    priority:
      name: 优先级
      description: 通知的优先级
      required: false
      default: "normal"
      selector:
        select:
          options:
            - "low"
            - "normal"
            - "high"
            - "urgent"
    led_color:
      name: LED颜色
      description: 通知时LED的颜色
      required: false
      default: "blue"
      selector:
        select:
          options:
            - "red"
            - "green"
            - "blue"
            - "yellow"
            - "purple" 