send_tts:
  name: 发送TTS消息
  description: 向指定XiaoZhi ESP32设备发送文本到语音消息
  fields:
    device_id:
      name: 设备ID
      description: XiaoZhi ESP32设备的唯一标识符
      required: true
      selector:
        text:
    message:
      name: 消息内容
      description: 需要播放的文本内容
      required: true
      selector:
        text:

get_device_config:
  name: 获取设备配置
  description: 获取用于ESP32设备配置的信息
  fields:
    config_entry_id:
      name: 配置条目ID
      description: XiaoZhi集成配置条目的ID
      required: true
      selector:
        text:
    device_id:
      name: 设备ID
      description: XiaoZhi ESP32设备的唯一标识符，如不提供将自动生成
      required: false
      selector:
        text:
    fallback_url:
      name: 备选URL
      description: 如果无法确定Home Assistant外部URL，使用此URL作为备选
      required: false
      selector:
        text: 